Fix compile error: client.c:1355:5: error: conflicting types for 'recvmmsg'
$ make
cc -O2 -Wall -g -fPIC   -c -o client.o client.c
client.c:1355:5: error: conflicting types for ‘recvmmsg’
 int recvmmsg(int sockfd, struct mmsghdr *msgvec, unsigned int vlen, int flags, struct timespec *timeout) {
     ^
In file included from client.c:23:0:
/usr/include/sys/socket.h:211:12: note: previous declaration of ‘recvmmsg’ was here
 extern int recvmmsg (int __fd, struct mmsghdr *__vmessages,
            ^
make: *** [client.o] Error 1

Because it have the same function name with library function: /usr/include/sys/socket.h:211.
And i saw it has not been called, so i think we can change it to recvmmsg_inner

Signed-off-by: Qiao Zhao <qzhao@redhat.com>